//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:55:54 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.RealTimePaymentByAgency;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RealTmPmtByAgcyInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RealTmPmtByAgcyInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BtchNb" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}Max8NumericText"/>
 *         &lt;element name="RcvTp" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}Max4Text"/>
 *         &lt;element name="TxId" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}Max16NumericText"/>
 *         &lt;element name="Dbtr" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}DbtrCdtr1"/>
 *         &lt;element name="DbtrAcct" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}DbtrCdtrAcct1"/>
 *         &lt;element name="DbtrAgt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}DbtrCdtrAgt1"/>
 *         &lt;element name="CdtrAgt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}DbtrCdtrAgt1"/>
 *         &lt;element name="Cdtr" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}DbtrCdtr1"/>
 *         &lt;element name="CdtrAcct" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}DbtrCdtrAcct1"/>
 *         &lt;element name="Amt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}ActiveCurrencyAndAmount"/>
 *         &lt;element name="PmtTpInf" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}PmtTpInf1"/>
 *         &lt;element name="Purp" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}Purp1"/>
 *         &lt;element name="EndToEndId" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}Max60Text" minOccurs="0"/>
 *         &lt;element name="ChckFlg" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}ChckFlgCode1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RealTmPmtByAgcyInf1", propOrder = {
    "btchNb",
    "rcvTp",
    "txId",
    "dbtr",
    "dbtrAcct",
    "dbtrAgt",
    "cdtrAgt",
    "cdtr",
    "cdtrAcct",
    "amt",
    "pmtTpInf",
    "purp",
    "endToEndId",
    "chckFlg"
})
public class RealTmPmtByAgcyInf1 {

    @XmlElement(name = "BtchNb", required = true)
    protected String btchNb;
    @XmlElement(name = "RcvTp", required = true)
    protected String rcvTp;
    @XmlElement(name = "TxId", required = true)
    protected String txId;
    @XmlElement(name = "Dbtr", required = true)
    protected DbtrCdtr1 dbtr;
    @XmlElement(name = "DbtrAcct", required = true)
    protected DbtrCdtrAcct1 dbtrAcct;
    @XmlElement(name = "DbtrAgt", required = true)
    protected DbtrCdtrAgt1 dbtrAgt;
    @XmlElement(name = "CdtrAgt", required = true)
    protected DbtrCdtrAgt1 cdtrAgt;
    @XmlElement(name = "Cdtr", required = true)
    protected DbtrCdtr1 cdtr;
    @XmlElement(name = "CdtrAcct", required = true)
    protected DbtrCdtrAcct1 cdtrAcct;
    @XmlElement(name = "Amt", required = true)
    protected ActiveCurrencyAndAmount amt;
    @XmlElement(name = "PmtTpInf", required = true)
    protected PmtTpInf1 pmtTpInf;
    @XmlElement(name = "Purp", required = true)
    protected Purp1 purp;
    @XmlElement(name = "EndToEndId")
    protected String endToEndId;
    @XmlElement(name = "ChckFlg", required = true)
    protected ChckFlgCode1 chckFlg;

    /**
     * Gets the value of the btchNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBtchNb() {
        return btchNb;
    }

    /**
     * Sets the value of the btchNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBtchNb(String value) {
        this.btchNb = value;
    }

    /**
     * Gets the value of the rcvTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvTp() {
        return rcvTp;
    }

    /**
     * Sets the value of the rcvTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvTp(String value) {
        this.rcvTp = value;
    }

    /**
     * Gets the value of the txId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxId() {
        return txId;
    }

    /**
     * Sets the value of the txId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxId(String value) {
        this.txId = value;
    }

    /**
     * Gets the value of the dbtr property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtr1 }
     *     
     */
    public DbtrCdtr1 getDbtr() {
        return dbtr;
    }

    /**
     * Sets the value of the dbtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtr1 }
     *     
     */
    public void setDbtr(DbtrCdtr1 value) {
        this.dbtr = value;
    }

    /**
     * Gets the value of the dbtrAcct property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtrAcct1 }
     *     
     */
    public DbtrCdtrAcct1 getDbtrAcct() {
        return dbtrAcct;
    }

    /**
     * Sets the value of the dbtrAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtrAcct1 }
     *     
     */
    public void setDbtrAcct(DbtrCdtrAcct1 value) {
        this.dbtrAcct = value;
    }

    /**
     * Gets the value of the dbtrAgt property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtrAgt1 }
     *     
     */
    public DbtrCdtrAgt1 getDbtrAgt() {
        return dbtrAgt;
    }

    /**
     * Sets the value of the dbtrAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtrAgt1 }
     *     
     */
    public void setDbtrAgt(DbtrCdtrAgt1 value) {
        this.dbtrAgt = value;
    }

    /**
     * Gets the value of the cdtrAgt property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtrAgt1 }
     *     
     */
    public DbtrCdtrAgt1 getCdtrAgt() {
        return cdtrAgt;
    }

    /**
     * Sets the value of the cdtrAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtrAgt1 }
     *     
     */
    public void setCdtrAgt(DbtrCdtrAgt1 value) {
        this.cdtrAgt = value;
    }

    /**
     * Gets the value of the cdtr property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtr1 }
     *     
     */
    public DbtrCdtr1 getCdtr() {
        return cdtr;
    }

    /**
     * Sets the value of the cdtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtr1 }
     *     
     */
    public void setCdtr(DbtrCdtr1 value) {
        this.cdtr = value;
    }

    /**
     * Gets the value of the cdtrAcct property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtrAcct1 }
     *     
     */
    public DbtrCdtrAcct1 getCdtrAcct() {
        return cdtrAcct;
    }

    /**
     * Sets the value of the cdtrAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtrAcct1 }
     *     
     */
    public void setCdtrAcct(DbtrCdtrAcct1 value) {
        this.cdtrAcct = value;
    }

    /**
     * Gets the value of the amt property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public ActiveCurrencyAndAmount getAmt() {
        return amt;
    }

    /**
     * Sets the value of the amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public void setAmt(ActiveCurrencyAndAmount value) {
        this.amt = value;
    }

    /**
     * Gets the value of the pmtTpInf property.
     * 
     * @return
     *     possible object is
     *     {@link PmtTpInf1 }
     *     
     */
    public PmtTpInf1 getPmtTpInf() {
        return pmtTpInf;
    }

    /**
     * Sets the value of the pmtTpInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtTpInf1 }
     *     
     */
    public void setPmtTpInf(PmtTpInf1 value) {
        this.pmtTpInf = value;
    }

    /**
     * Gets the value of the purp property.
     * 
     * @return
     *     possible object is
     *     {@link Purp1 }
     *     
     */
    public Purp1 getPurp() {
        return purp;
    }

    /**
     * Sets the value of the purp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Purp1 }
     *     
     */
    public void setPurp(Purp1 value) {
        this.purp = value;
    }

    /**
     * Gets the value of the endToEndId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndToEndId() {
        return endToEndId;
    }

    /**
     * Sets the value of the endToEndId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndToEndId(String value) {
        this.endToEndId = value;
    }

    /**
     * Gets the value of the chckFlg property.
     * 
     * @return
     *     possible object is
     *     {@link ChckFlgCode1 }
     *     
     */
    public ChckFlgCode1 getChckFlg() {
        return chckFlg;
    }

    /**
     * Sets the value of the chckFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChckFlgCode1 }
     *     
     */
    public void setChckFlg(ChckFlgCode1 value) {
        this.chckFlg = value;
    }

}
