//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:55:54 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.RealTimePaymentByAgency;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RealTmPmtByAgcyV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RealTmPmtByAgcyV01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrpHdr" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}GroupHeader1"/>
 *         &lt;element name="RealTmPmtByAgcyInf" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.386.001.01}RealTmPmtByAgcyInf1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RealTmPmtByAgcyV01", propOrder = {
    "grpHdr",
    "realTmPmtByAgcyInf"
})
public class RealTmPmtByAgcyV01 {

    @XmlElement(name = "GrpHdr", required = true)
    protected GroupHeader1 grpHdr;
    @XmlElement(name = "RealTmPmtByAgcyInf", required = true)
    protected RealTmPmtByAgcyInf1 realTmPmtByAgcyInf;

    /**
     * Gets the value of the grpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link GroupHeader1 }
     *     
     */
    public GroupHeader1 getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupHeader1 }
     *     
     */
    public void setGrpHdr(GroupHeader1 value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the realTmPmtByAgcyInf property.
     * 
     * @return
     *     possible object is
     *     {@link RealTmPmtByAgcyInf1 }
     *     
     */
    public RealTmPmtByAgcyInf1 getRealTmPmtByAgcyInf() {
        return realTmPmtByAgcyInf;
    }

    /**
     * Sets the value of the realTmPmtByAgcyInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealTmPmtByAgcyInf1 }
     *     
     */
    public void setRealTmPmtByAgcyInf(RealTmPmtByAgcyInf1 value) {
        this.realTmPmtByAgcyInf = value;
    }

}
