//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:55:09 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.batchpaymentbyagency;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BtchPmtByAgcyV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BtchPmtByAgcyV01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrpHdr" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}GroupHeader1"/>
 *         &lt;element name="BtchPmtByAgcyInf" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}BtchPmtByAgcyInf1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BtchPmtByAgcyV01", propOrder = {
    "grpHdr",
    "btchPmtByAgcyInf"
})
public class BtchPmtByAgcyV01 {

    @XmlElement(name = "GrpHdr", required = true)
    protected GroupHeader1 grpHdr;
    @XmlElement(name = "BtchPmtByAgcyInf", required = true)
    protected BtchPmtByAgcyInf1 btchPmtByAgcyInf;

    /**
     * Gets the value of the grpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link GroupHeader1 }
     *     
     */
    public GroupHeader1 getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupHeader1 }
     *     
     */
    public void setGrpHdr(GroupHeader1 value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the btchPmtByAgcyInf property.
     * 
     * @return
     *     possible object is
     *     {@link BtchPmtByAgcyInf1 }
     *     
     */
    public BtchPmtByAgcyInf1 getBtchPmtByAgcyInf() {
        return btchPmtByAgcyInf;
    }

    /**
     * Sets the value of the btchPmtByAgcyInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BtchPmtByAgcyInf1 }
     *     
     */
    public void setBtchPmtByAgcyInf(BtchPmtByAgcyInf1 value) {
        this.btchPmtByAgcyInf = value;
    }

}
