//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:55:09 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.batchpaymentbyagency;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BtchPmtByAgcyInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BtchPmtByAgcyInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BtchNb" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}Max8NumericText"/>
 *         &lt;element name="TrnsmtSndrDt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}ISODate" minOccurs="0"/>
 *         &lt;element name="TrnsmtRcvrDt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}ISODate" minOccurs="0"/>
 *         &lt;element name="RtrLtd" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}Max2NumericText"/>
 *         &lt;element name="RcvTp" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}Max4Text"/>
 *         &lt;element name="EndToEndId" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}Max60Text" minOccurs="0"/>
 *         &lt;element name="ChckFlg" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}ChckFlgCode1"/>
 *         &lt;element name="Dbtr" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}DbtrCdtr1"/>
 *         &lt;element name="DbtrAcct" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}DbtrCdtrAcct1"/>
 *         &lt;element name="DbtrAgt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}DbtrAgt1"/>
 *         &lt;element name="CdtrAgt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}CdtrAgt1"/>
 *         &lt;element name="TtlAmt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}ActiveCurrencyAndAmount"/>
 *         &lt;element name="PmtTpInf" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}PmtTpInf1"/>
 *         &lt;element name="CdtrNb" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}Max8NumericText"/>
 *         &lt;element name="CdtrDtls" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}CdtrDtls1" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BtchPmtByAgcyInf1", propOrder = {
    "btchNb",
    "trnsmtSndrDt",
    "trnsmtRcvrDt",
    "rtrLtd",
    "rcvTp",
    "endToEndId",
    "chckFlg",
    "dbtr",
    "dbtrAcct",
    "dbtrAgt",
    "cdtrAgt",
    "ttlAmt",
    "pmtTpInf",
    "cdtrNb",
    "cdtrDtls"
})
public class BtchPmtByAgcyInf1 {

    @XmlElement(name = "BtchNb", required = true)
    protected String btchNb;
    @XmlElement(name = "TrnsmtSndrDt")
    protected XMLGregorianCalendar trnsmtSndrDt;
    @XmlElement(name = "TrnsmtRcvrDt")
    protected XMLGregorianCalendar trnsmtRcvrDt;
    @XmlElement(name = "RtrLtd", required = true)
    protected String rtrLtd;
    @XmlElement(name = "RcvTp", required = true)
    protected String rcvTp;
    @XmlElement(name = "EndToEndId")
    protected String endToEndId;
    @XmlElement(name = "ChckFlg", required = true)
    protected ChckFlgCode1 chckFlg;
    @XmlElement(name = "Dbtr", required = true)
    protected DbtrCdtr1 dbtr;
    @XmlElement(name = "DbtrAcct", required = true)
    protected DbtrCdtrAcct1 dbtrAcct;
    @XmlElement(name = "DbtrAgt", required = true)
    protected DbtrAgt1 dbtrAgt;
    @XmlElement(name = "CdtrAgt", required = true)
    protected CdtrAgt1 cdtrAgt;
    @XmlElement(name = "TtlAmt", required = true)
    protected ActiveCurrencyAndAmount ttlAmt;
    @XmlElement(name = "PmtTpInf", required = true)
    protected PmtTpInf1 pmtTpInf;
    @XmlElement(name = "CdtrNb", required = true)
    protected String cdtrNb;
    @XmlElement(name = "CdtrDtls", required = true)
    protected List<CdtrDtls1> cdtrDtls;

    /**
     * Gets the value of the btchNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBtchNb() {
        return btchNb;
    }

    /**
     * Sets the value of the btchNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBtchNb(String value) {
        this.btchNb = value;
    }

    /**
     * Gets the value of the trnsmtSndrDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrnsmtSndrDt() {
        return trnsmtSndrDt;
    }

    /**
     * Sets the value of the trnsmtSndrDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTrnsmtSndrDt(XMLGregorianCalendar value) {
        this.trnsmtSndrDt = value;
    }

    /**
     * Gets the value of the trnsmtRcvrDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrnsmtRcvrDt() {
        return trnsmtRcvrDt;
    }

    /**
     * Sets the value of the trnsmtRcvrDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTrnsmtRcvrDt(XMLGregorianCalendar value) {
        this.trnsmtRcvrDt = value;
    }

    /**
     * Gets the value of the rtrLtd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtrLtd() {
        return rtrLtd;
    }

    /**
     * Sets the value of the rtrLtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtrLtd(String value) {
        this.rtrLtd = value;
    }

    /**
     * Gets the value of the rcvTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvTp() {
        return rcvTp;
    }

    /**
     * Sets the value of the rcvTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvTp(String value) {
        this.rcvTp = value;
    }

    /**
     * Gets the value of the endToEndId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndToEndId() {
        return endToEndId;
    }

    /**
     * Sets the value of the endToEndId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndToEndId(String value) {
        this.endToEndId = value;
    }

    /**
     * Gets the value of the chckFlg property.
     * 
     * @return
     *     possible object is
     *     {@link ChckFlgCode1 }
     *     
     */
    public ChckFlgCode1 getChckFlg() {
        return chckFlg;
    }

    /**
     * Sets the value of the chckFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChckFlgCode1 }
     *     
     */
    public void setChckFlg(ChckFlgCode1 value) {
        this.chckFlg = value;
    }

    /**
     * Gets the value of the dbtr property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtr1 }
     *     
     */
    public DbtrCdtr1 getDbtr() {
        return dbtr;
    }

    /**
     * Sets the value of the dbtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtr1 }
     *     
     */
    public void setDbtr(DbtrCdtr1 value) {
        this.dbtr = value;
    }

    /**
     * Gets the value of the dbtrAcct property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtrAcct1 }
     *     
     */
    public DbtrCdtrAcct1 getDbtrAcct() {
        return dbtrAcct;
    }

    /**
     * Sets the value of the dbtrAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtrAcct1 }
     *     
     */
    public void setDbtrAcct(DbtrCdtrAcct1 value) {
        this.dbtrAcct = value;
    }

    /**
     * Gets the value of the dbtrAgt property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrAgt1 }
     *     
     */
    public DbtrAgt1 getDbtrAgt() {
        return dbtrAgt;
    }

    /**
     * Sets the value of the dbtrAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrAgt1 }
     *     
     */
    public void setDbtrAgt(DbtrAgt1 value) {
        this.dbtrAgt = value;
    }

    /**
     * Gets the value of the cdtrAgt property.
     * 
     * @return
     *     possible object is
     *     {@link CdtrAgt1 }
     *     
     */
    public CdtrAgt1 getCdtrAgt() {
        return cdtrAgt;
    }

    /**
     * Sets the value of the cdtrAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdtrAgt1 }
     *     
     */
    public void setCdtrAgt(CdtrAgt1 value) {
        this.cdtrAgt = value;
    }

    /**
     * Gets the value of the ttlAmt property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public ActiveCurrencyAndAmount getTtlAmt() {
        return ttlAmt;
    }

    /**
     * Sets the value of the ttlAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public void setTtlAmt(ActiveCurrencyAndAmount value) {
        this.ttlAmt = value;
    }

    /**
     * Gets the value of the pmtTpInf property.
     * 
     * @return
     *     possible object is
     *     {@link PmtTpInf1 }
     *     
     */
    public PmtTpInf1 getPmtTpInf() {
        return pmtTpInf;
    }

    /**
     * Sets the value of the pmtTpInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtTpInf1 }
     *     
     */
    public void setPmtTpInf(PmtTpInf1 value) {
        this.pmtTpInf = value;
    }

    /**
     * Gets the value of the cdtrNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrNb() {
        return cdtrNb;
    }

    /**
     * Sets the value of the cdtrNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrNb(String value) {
        this.cdtrNb = value;
    }

    /**
     * Gets the value of the cdtrDtls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cdtrDtls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCdtrDtls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CdtrDtls1 }
     * 
     * 
     */
    public List<CdtrDtls1> getCdtrDtls() {
        if (cdtrDtls == null) {
            cdtrDtls = new ArrayList<CdtrDtls1>();
        }
        return this.cdtrDtls;
    }

}
