//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:55:09 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.batchpaymentbyagency;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BtchPmtByAgcy" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.382.001.01}BtchPmtByAgcyV01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "btchPmtByAgcy"
})
public class Document {

    @XmlElement(name = "BtchPmtByAgcy", required = true)
    protected BtchPmtByAgcyV01 btchPmtByAgcy;

    /**
     * Gets the value of the btchPmtByAgcy property.
     * 
     * @return
     *     possible object is
     *     {@link BtchPmtByAgcyV01 }
     *     
     */
    public BtchPmtByAgcyV01 getBtchPmtByAgcy() {
        return btchPmtByAgcy;
    }

    /**
     * Sets the value of the btchPmtByAgcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BtchPmtByAgcyV01 }
     *     
     */
    public void setBtchPmtByAgcy(BtchPmtByAgcyV01 value) {
        this.btchPmtByAgcy = value;
    }

}
