//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:54:49 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.batchcollectioncharges;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BtchColltnChrgsInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BtchColltnChrgsInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BtchNb" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}Max8NumericText"/>
 *         &lt;element name="TrnsmtDt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}ISODate" minOccurs="0"/>
 *         &lt;element name="RtrLtd" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}Max2NumericText"/>
 *         &lt;element name="DbtrAgt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}DbtrAgt1"/>
 *         &lt;element name="CdtrAgt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}CdtrAgt1"/>
 *         &lt;element name="Cdtr" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}DbtrCdtr1"/>
 *         &lt;element name="CdtrAcct" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}DbtrCdtrAcct1"/>
 *         &lt;element name="TtlAmt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}ActiveCurrencyAndAmount"/>
 *         &lt;element name="PmtTpInf" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}PmtTpInf1"/>
 *         &lt;element name="DbtrNb" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}Max8NumericText"/>
 *         &lt;element name="DbtrDtls" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}DbtrDtls1" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BtchColltnChrgsInf1", propOrder = {
    "btchNb",
    "trnsmtDt",
    "rtrLtd",
    "dbtrAgt",
    "cdtrAgt",
    "cdtr",
    "cdtrAcct",
    "ttlAmt",
    "pmtTpInf",
    "dbtrNb",
    "dbtrDtls"
})
public class BtchColltnChrgsInf1 {

    @XmlElement(name = "BtchNb", required = true)
    protected String btchNb;
    @XmlElement(name = "TrnsmtDt")
    protected XMLGregorianCalendar trnsmtDt;
    @XmlElement(name = "RtrLtd", required = true)
    protected String rtrLtd;
    @XmlElement(name = "DbtrAgt", required = true)
    protected DbtrAgt1 dbtrAgt;
    @XmlElement(name = "CdtrAgt", required = true)
    protected CdtrAgt1 cdtrAgt;
    @XmlElement(name = "Cdtr", required = true)
    protected DbtrCdtr1 cdtr;
    @XmlElement(name = "CdtrAcct", required = true)
    protected DbtrCdtrAcct1 cdtrAcct;
    @XmlElement(name = "TtlAmt", required = true)
    protected ActiveCurrencyAndAmount ttlAmt;
    @XmlElement(name = "PmtTpInf", required = true)
    protected PmtTpInf1 pmtTpInf;
    @XmlElement(name = "DbtrNb", required = true)
    protected String dbtrNb;
    @XmlElement(name = "DbtrDtls", required = true)
    protected List<DbtrDtls1> dbtrDtls;

    /**
     * Gets the value of the btchNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBtchNb() {
        return btchNb;
    }

    /**
     * Sets the value of the btchNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBtchNb(String value) {
        this.btchNb = value;
    }

    /**
     * Gets the value of the trnsmtDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrnsmtDt() {
        return trnsmtDt;
    }

    /**
     * Sets the value of the trnsmtDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTrnsmtDt(XMLGregorianCalendar value) {
        this.trnsmtDt = value;
    }

    /**
     * Gets the value of the rtrLtd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtrLtd() {
        return rtrLtd;
    }

    /**
     * Sets the value of the rtrLtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtrLtd(String value) {
        this.rtrLtd = value;
    }

    /**
     * Gets the value of the dbtrAgt property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrAgt1 }
     *     
     */
    public DbtrAgt1 getDbtrAgt() {
        return dbtrAgt;
    }

    /**
     * Sets the value of the dbtrAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrAgt1 }
     *     
     */
    public void setDbtrAgt(DbtrAgt1 value) {
        this.dbtrAgt = value;
    }

    /**
     * Gets the value of the cdtrAgt property.
     * 
     * @return
     *     possible object is
     *     {@link CdtrAgt1 }
     *     
     */
    public CdtrAgt1 getCdtrAgt() {
        return cdtrAgt;
    }

    /**
     * Sets the value of the cdtrAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdtrAgt1 }
     *     
     */
    public void setCdtrAgt(CdtrAgt1 value) {
        this.cdtrAgt = value;
    }

    /**
     * Gets the value of the cdtr property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtr1 }
     *     
     */
    public DbtrCdtr1 getCdtr() {
        return cdtr;
    }

    /**
     * Sets the value of the cdtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtr1 }
     *     
     */
    public void setCdtr(DbtrCdtr1 value) {
        this.cdtr = value;
    }

    /**
     * Gets the value of the cdtrAcct property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtrAcct1 }
     *     
     */
    public DbtrCdtrAcct1 getCdtrAcct() {
        return cdtrAcct;
    }

    /**
     * Sets the value of the cdtrAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtrAcct1 }
     *     
     */
    public void setCdtrAcct(DbtrCdtrAcct1 value) {
        this.cdtrAcct = value;
    }

    /**
     * Gets the value of the ttlAmt property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public ActiveCurrencyAndAmount getTtlAmt() {
        return ttlAmt;
    }

    /**
     * Sets the value of the ttlAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public void setTtlAmt(ActiveCurrencyAndAmount value) {
        this.ttlAmt = value;
    }

    /**
     * Gets the value of the pmtTpInf property.
     * 
     * @return
     *     possible object is
     *     {@link PmtTpInf1 }
     *     
     */
    public PmtTpInf1 getPmtTpInf() {
        return pmtTpInf;
    }

    /**
     * Sets the value of the pmtTpInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmtTpInf1 }
     *     
     */
    public void setPmtTpInf(PmtTpInf1 value) {
        this.pmtTpInf = value;
    }

    /**
     * Gets the value of the dbtrNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrNb() {
        return dbtrNb;
    }

    /**
     * Sets the value of the dbtrNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrNb(String value) {
        this.dbtrNb = value;
    }

    /**
     * Gets the value of the dbtrDtls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dbtrDtls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDbtrDtls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DbtrDtls1 }
     * 
     * 
     */
    public List<DbtrDtls1> getDbtrDtls() {
        if (dbtrDtls == null) {
            dbtrDtls = new ArrayList<DbtrDtls1>();
        }
        return this.dbtrDtls;
    }

}
