//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:54:49 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.batchcollectioncharges;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BtchColltnChrgs" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.380.001.01}BtchColltnChrgsV01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "btchColltnChrgs"
})
public class Document {

    @XmlElement(name = "BtchColltnChrgs", required = true)
    protected BtchColltnChrgsV01 btchColltnChrgs;

    /**
     * Gets the value of the btchColltnChrgs property.
     * 
     * @return
     *     possible object is
     *     {@link BtchColltnChrgsV01 }
     *     
     */
    public BtchColltnChrgsV01 getBtchColltnChrgs() {
        return btchColltnChrgs;
    }

    /**
     * Sets the value of the btchColltnChrgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BtchColltnChrgsV01 }
     *     
     */
    public void setBtchColltnChrgs(BtchColltnChrgsV01 value) {
        this.btchColltnChrgs = value;
    }

}
