//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:55:29 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.RealTimeCollectionCharges;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RealTmColltnChrgsV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RealTmColltnChrgsV01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrpHdr" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.384.001.01}GroupHeader1"/>
 *         &lt;element name="RealTmColltnChrgsInf" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.384.001.01}RealTmColltnChrgsInf1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RealTmColltnChrgsV01", propOrder = {
    "grpHdr",
    "realTmColltnChrgsInf"
})
public class RealTmColltnChrgsV01 {

    @XmlElement(name = "GrpHdr", required = true)
    protected GroupHeader1 grpHdr;
    @XmlElement(name = "RealTmColltnChrgsInf", required = true)
    protected RealTmColltnChrgsInf1 realTmColltnChrgsInf;

    /**
     * Gets the value of the grpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link GroupHeader1 }
     *     
     */
    public GroupHeader1 getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupHeader1 }
     *     
     */
    public void setGrpHdr(GroupHeader1 value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the realTmColltnChrgsInf property.
     * 
     * @return
     *     possible object is
     *     {@link RealTmColltnChrgsInf1 }
     *     
     */
    public RealTmColltnChrgsInf1 getRealTmColltnChrgsInf() {
        return realTmColltnChrgsInf;
    }

    /**
     * Sets the value of the realTmColltnChrgsInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealTmColltnChrgsInf1 }
     *     
     */
    public void setRealTmColltnChrgsInf(RealTmColltnChrgsInf1 value) {
        this.realTmColltnChrgsInf = value;
    }

}
