//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:55:19 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.batchpaymentbyagencyresponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BtchPmtByAgcyRspnInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BtchPmtByAgcyRspnInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SndgTtlAmt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.383.001.01}ActiveCurrencyAndAmount"/>
 *         &lt;element name="SndgTtlNb" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.383.001.01}Max8NumericText"/>
 *         &lt;element name="DbtrAgt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.383.001.01}DbtrAgt1"/>
 *         &lt;element name="Dbtr" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.383.001.01}DbtrCdtr1"/>
 *         &lt;element name="DbtrAcct" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.383.001.01}DbtrCdtrAcct1"/>
 *         &lt;element name="SndgDtls" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.383.001.01}SndgDtls1" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BtchPmtByAgcyRspnInf1", propOrder = {
    "sndgTtlAmt",
    "sndgTtlNb",
    "dbtrAgt",
    "dbtr",
    "dbtrAcct",
    "sndgDtls"
})
public class BtchPmtByAgcyRspnInf1 {

    @XmlElement(name = "SndgTtlAmt", required = true)
    protected ActiveCurrencyAndAmount sndgTtlAmt;
    @XmlElement(name = "SndgTtlNb", required = true)
    protected String sndgTtlNb;
    @XmlElement(name = "DbtrAgt", required = true)
    protected DbtrAgt1 dbtrAgt;
    @XmlElement(name = "Dbtr", required = true)
    protected DbtrCdtr1 dbtr;
    @XmlElement(name = "DbtrAcct", required = true)
    protected DbtrCdtrAcct1 dbtrAcct;
    @XmlElement(name = "SndgDtls", required = true)
    protected List<SndgDtls1> sndgDtls;

    /**
     * Gets the value of the sndgTtlAmt property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public ActiveCurrencyAndAmount getSndgTtlAmt() {
        return sndgTtlAmt;
    }

    /**
     * Sets the value of the sndgTtlAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public void setSndgTtlAmt(ActiveCurrencyAndAmount value) {
        this.sndgTtlAmt = value;
    }

    /**
     * Gets the value of the sndgTtlNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndgTtlNb() {
        return sndgTtlNb;
    }

    /**
     * Sets the value of the sndgTtlNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndgTtlNb(String value) {
        this.sndgTtlNb = value;
    }

    /**
     * Gets the value of the dbtrAgt property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrAgt1 }
     *     
     */
    public DbtrAgt1 getDbtrAgt() {
        return dbtrAgt;
    }

    /**
     * Sets the value of the dbtrAgt property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrAgt1 }
     *     
     */
    public void setDbtrAgt(DbtrAgt1 value) {
        this.dbtrAgt = value;
    }

    /**
     * Gets the value of the dbtr property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtr1 }
     *     
     */
    public DbtrCdtr1 getDbtr() {
        return dbtr;
    }

    /**
     * Sets the value of the dbtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtr1 }
     *     
     */
    public void setDbtr(DbtrCdtr1 value) {
        this.dbtr = value;
    }

    /**
     * Gets the value of the dbtrAcct property.
     * 
     * @return
     *     possible object is
     *     {@link DbtrCdtrAcct1 }
     *     
     */
    public DbtrCdtrAcct1 getDbtrAcct() {
        return dbtrAcct;
    }

    /**
     * Sets the value of the dbtrAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbtrCdtrAcct1 }
     *     
     */
    public void setDbtrAcct(DbtrCdtrAcct1 value) {
        this.dbtrAcct = value;
    }

    /**
     * Gets the value of the sndgDtls property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sndgDtls property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSndgDtls().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SndgDtls1 }
     * 
     * 
     */
    public List<SndgDtls1> getSndgDtls() {
        if (sndgDtls == null) {
            sndgDtls = new ArrayList<SndgDtls1>();
        }
        return this.sndgDtls;
    }

}
