package com.zcbspay.platform.channel.unionpay.withholding.pojo;

// default package
// Generated 2017-1-13 13:30:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * TTxnsLogUp generated by hbm2java
 */
@Entity
@Table(name = "T_TXNS_LOG_UP")
public class PojoTxnsLogUp implements java.io.Serializable {

	private static final long serialVersionUID = 6560195388362675932L;
	private String orderId;
	private String version;
	private String refOrderId;
	private String txnseqno;
	private String tradeStatus;
	private String encoding;
	private String certId;
	private String signMethod;
	private String transType;
	private String mchntCd;
	private String factorId;
	private String priAcctId;
	private String name;
	private String phone;
	private String idCard;
	private String dkType;
	private long transAt;
	private String atType;
	private String transTm;
	private String backUrl;
	private String respcod;
	private String respmsg;
	private long settleAt;
	private String settleType;
	private String settleDate;
	private String exchangeDate;
	private String exchangeRate;
	private String queryTm;
    private String transDt;
    private String downloadUrl;
    
    
    

	public PojoTxnsLogUp() {
	}

	public PojoTxnsLogUp(String orderId, String txnseqno, String tradeStatus,
			String transType, String mchntCd, long transAt, String atType) {
		this.orderId = orderId;
		this.txnseqno = txnseqno;
		this.tradeStatus = tradeStatus;
		this.transType = transType;
		this.mchntCd = mchntCd;
		this.transAt = transAt;
		this.atType = atType;
	}

	public PojoTxnsLogUp(String orderId, String refOrderId, String txnseqno,
			String tradeStatus, String encoding, String certId,
			String signature, String signMethod, String transType,
			String mchntCd, String factorId, String priAcctId, String name,
			String phone, String idCard, String dkType, long transAt,
			String atType, String transTm, String backUrl, String respcod,
			String respmsg, long settleAt, String settleType,
			String settleDate, String exchangeDate, String exchangeRate, String queryTm,
            String transDt, String downloadUrl) {
		this.orderId = orderId;
		this.refOrderId = refOrderId;
		this.txnseqno = txnseqno;
		this.tradeStatus = tradeStatus;
		this.encoding = encoding;
		this.certId = certId;
		this.signMethod = signMethod;
		this.transType = transType;
		this.mchntCd = mchntCd;
		this.factorId = factorId;
		this.priAcctId = priAcctId;
		this.name = name;
		this.phone = phone;
		this.idCard = idCard;
		this.dkType = dkType;
		this.transAt = transAt;
		this.atType = atType;
		this.transTm = transTm;
		this.backUrl = backUrl;
		this.respcod = respcod;
		this.respmsg = respmsg;
		this.settleAt = settleAt;
		this.settleType = settleType;
		this.settleDate = settleDate;
		this.exchangeDate = exchangeDate;
		this.exchangeRate = exchangeRate;
		this.queryTm = queryTm;
		this.transDt = transDt;
		this.downloadUrl = downloadUrl;
	}

	@Id
	@Column(name = "ORDER_ID", unique = true, nullable = false, length = 32)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	
	@Column(name = "VERSION", length = 5)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "REF_ORDER_ID", length = 32)
	public String getRefOrderId() {
		return this.refOrderId;
	}

	public void setRefOrderId(String refOrderId) {
		this.refOrderId = refOrderId;
	}

	@Column(name = "TXNSEQNO", length = 16)
	public String getTxnseqno() {
		return this.txnseqno;
	}

	public void setTxnseqno(String txnseqno) {
		this.txnseqno = txnseqno;
	}

	@Column(name = "TRADE_STATUS", length = 32)
	public String getTradeStatus() {
		return this.tradeStatus;
	}

	public void setTradeStatus(String tradeStatus) {
		this.tradeStatus = tradeStatus;
	}

	@Column(name = "ENCODING", length = 5)
	public String getEncoding() {
		return this.encoding;
	}

	public void setEncoding(String encoding) {
		this.encoding = encoding;
	}

	@Column(name = "CERT_ID", length = 20)
	public String getCertId() {
		return this.certId;
	}

	public void setCertId(String certId) {
		this.certId = certId;
	}

	@Column(name = "SIGN_METHOD", length = 2)
	public String getSignMethod() {
		return this.signMethod;
	}

	public void setSignMethod(String signMethod) {
		this.signMethod = signMethod;
	}

	@Column(name = "TRANS_TYPE", nullable = false, length = 2)
	public String getTransType() {
		return this.transType;
	}

	public void setTransType(String transType) {
		this.transType = transType;
	}

	@Column(name = "MCHNT_CD", nullable = false, length = 15)
	public String getMchntCd() {
		return this.mchntCd;
	}

	public void setMchntCd(String mchntCd) {
		this.mchntCd = mchntCd;
	}

	@Column(name = "FACTOR_ID", length = 4)
	public String getFactorId() {
		return this.factorId;
	}

	public void setFactorId(String factorId) {
		this.factorId = factorId;
	}

	@Column(name = "PRI_ACCT_ID", length = 22)
	public String getPriAcctId() {
		return this.priAcctId;
	}

	public void setPriAcctId(String priAcctId) {
		this.priAcctId = priAcctId;
	}

	@Column(name = "NAME", length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PHONE", length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "ID_CARD", length = 20)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "DK_TYPE", length = 1)
	public String getDkType() {
		return this.dkType;
	}

	public void setDkType(String dkType) {
		this.dkType = dkType;
	}

	@Column(name = "TRANS_AT", nullable = false, precision = 12, scale = 0)
	public long getTransAt() {
		return this.transAt;
	}

	public void setTransAt(long transAt) {
		this.transAt = transAt;
	}

	@Column(name = "AT_TYPE", length = 3)
	public String getAtType() {
		return this.atType;
	}

	public void setAtType(String atType) {
		this.atType = atType;
	}

	@Column(name = "TRANS_TM", length = 8)
	public String getTransTm() {
		return this.transTm;
	}

	public void setTransTm(String transTm) {
		this.transTm = transTm;
	}

	@Column(name = "BACK_URL", length = 512)
	public String getBackUrl() {
		return this.backUrl;
	}

	public void setBackUrl(String backUrl) {
		this.backUrl = backUrl;
	}

	@Column(name = "RESPCOD", length = 4)
	public String getRespcod() {
		return this.respcod;
	}

	public void setRespcod(String respcod) {
		this.respcod = respcod;
	}

	@Column(name = "RESPMSG", length = 128)
	public String getRespmsg() {
		return this.respmsg;
	}

	public void setRespmsg(String respmsg) {
		this.respmsg = respmsg;
	}

	@Column(name = "SETTLE_AT", precision = 12, scale = 0)
	public long getSettleAt() {
		return this.settleAt;
	}

	public void setSettleAt(long settleAt) {
		this.settleAt = settleAt;
	}

	@Column(name = "SETTLE_TYPE", length = 3)
	public String getSettleType() {
		return this.settleType;
	}

	public void setSettleType(String settleType) {
		this.settleType = settleType;
	}

	@Column(name = "SETTLE_DATE", length = 8)
	public String getSettleDate() {
		return this.settleDate;
	}

	public void setSettleDate(String settleDate) {
		this.settleDate = settleDate;
	}

	@Column(name = "EXCHANGE_DATE", length = 8)
	public String getExchangeDate() {
		return this.exchangeDate;
	}

	public void setExchangeDate(String exchangeDate) {
		this.exchangeDate = exchangeDate;
	}

	@Column(name = "EXCHANGE_RATE", length = 8)
	public String getExchangeRate() {
		return this.exchangeRate;
	}

	public void setExchangeRate(String exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	@Column(name = "QUERY_TM", length = 14)
	public String getQueryTm() {
		return this.queryTm;
	}

	public void setQueryTm(String queryTm) {
		this.queryTm = queryTm;
	}

	@Column(name = "TRANS_DT", length = 8)
	public String getTransDt() {
		return this.transDt;
	}

	public void setTransDt(String transDt) {
		this.transDt = transDt;
	}

	@Column(name = "DOWNLOAD_URL", length = 512)
	public String getDownloadUrl() {
		return this.downloadUrl;
	}

	public void setDownloadUrl(String downloadUrl) {
		this.downloadUrl = downloadUrl;
	}

}
