//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:55:00 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.batchcollectionchargesresponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OrgnlMsgInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrgnlMsgInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrgnlMsgId" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.381.001.01}Max35Text"/>
 *         &lt;element name="OrgnlInstgPty" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.381.001.01}Max14Text"/>
 *         &lt;element name="OrgnlBtchNb" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.381.001.01}Max8NumericText"/>
 *         &lt;element name="OrgnlTrnsmtDt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.381.001.01}ISODate"/>
 *         &lt;element name="OrgnlRtrLtd" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.381.001.01}Max2NumericText"/>
 *         &lt;element name="OrgnlTtlAmt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.381.001.01}ActiveCurrencyAndAmount"/>
 *         &lt;element name="OrgnlTtlNb" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.381.001.01}Max8NumericText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrgnlMsgInf1", propOrder = {
    "orgnlMsgId",
    "orgnlInstgPty",
    "orgnlBtchNb",
    "orgnlTrnsmtDt",
    "orgnlRtrLtd",
    "orgnlTtlAmt",
    "orgnlTtlNb"
})
public class OrgnlMsgInf1 {

    @XmlElement(name = "OrgnlMsgId", required = true)
    protected String orgnlMsgId;
    @XmlElement(name = "OrgnlInstgPty", required = true)
    protected String orgnlInstgPty;
    @XmlElement(name = "OrgnlBtchNb", required = true)
    protected String orgnlBtchNb;
    @XmlElement(name = "OrgnlTrnsmtDt", required = true)
    protected XMLGregorianCalendar orgnlTrnsmtDt;
    @XmlElement(name = "OrgnlRtrLtd", required = true)
    protected String orgnlRtrLtd;
    @XmlElement(name = "OrgnlTtlAmt", required = true)
    protected ActiveCurrencyAndAmount orgnlTtlAmt;
    @XmlElement(name = "OrgnlTtlNb", required = true)
    protected String orgnlTtlNb;

    /**
     * Gets the value of the orgnlMsgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnlMsgId() {
        return orgnlMsgId;
    }

    /**
     * Sets the value of the orgnlMsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnlMsgId(String value) {
        this.orgnlMsgId = value;
    }

    /**
     * Gets the value of the orgnlInstgPty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnlInstgPty() {
        return orgnlInstgPty;
    }

    /**
     * Sets the value of the orgnlInstgPty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnlInstgPty(String value) {
        this.orgnlInstgPty = value;
    }

    /**
     * Gets the value of the orgnlBtchNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnlBtchNb() {
        return orgnlBtchNb;
    }

    /**
     * Sets the value of the orgnlBtchNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnlBtchNb(String value) {
        this.orgnlBtchNb = value;
    }

    /**
     * Gets the value of the orgnlTrnsmtDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrgnlTrnsmtDt() {
        return orgnlTrnsmtDt;
    }

    /**
     * Sets the value of the orgnlTrnsmtDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrgnlTrnsmtDt(XMLGregorianCalendar value) {
        this.orgnlTrnsmtDt = value;
    }

    /**
     * Gets the value of the orgnlRtrLtd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnlRtrLtd() {
        return orgnlRtrLtd;
    }

    /**
     * Sets the value of the orgnlRtrLtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnlRtrLtd(String value) {
        this.orgnlRtrLtd = value;
    }

    /**
     * Gets the value of the orgnlTtlAmt property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public ActiveCurrencyAndAmount getOrgnlTtlAmt() {
        return orgnlTtlAmt;
    }

    /**
     * Sets the value of the orgnlTtlAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveCurrencyAndAmount }
     *     
     */
    public void setOrgnlTtlAmt(ActiveCurrencyAndAmount value) {
        this.orgnlTtlAmt = value;
    }

    /**
     * Gets the value of the orgnlTtlNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgnlTtlNb() {
        return orgnlTtlNb;
    }

    /**
     * Sets the value of the orgnlTtlNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgnlTtlNb(String value) {
        this.orgnlTtlNb = value;
    }

}
