//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 04:56:21 PM CST 
//


package com.zcbspay.platform.channel.beps.bean.BusinessRejectNotice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BizRjctNtceV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BizRjctNtceV01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrpHdr" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.388.001.01}GroupHeader1"/>
 *         &lt;element name="OrgnlMsgInf" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.388.001.01}OrgnlMsgInf1"/>
 *         &lt;element name="BizRjctNtceInf" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.388.001.01}BizRjctNtceInf1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BizRjctNtceV01", propOrder = {
    "grpHdr",
    "orgnlMsgInf",
    "bizRjctNtceInf"
})
public class BizRjctNtceV01 {

    @XmlElement(name = "GrpHdr", required = true)
    protected GroupHeader1 grpHdr;
    @XmlElement(name = "OrgnlMsgInf", required = true)
    protected OrgnlMsgInf1 orgnlMsgInf;
    @XmlElement(name = "BizRjctNtceInf", required = true)
    protected BizRjctNtceInf1 bizRjctNtceInf;

    /**
     * Gets the value of the grpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link GroupHeader1 }
     *     
     */
    public GroupHeader1 getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupHeader1 }
     *     
     */
    public void setGrpHdr(GroupHeader1 value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the orgnlMsgInf property.
     * 
     * @return
     *     possible object is
     *     {@link OrgnlMsgInf1 }
     *     
     */
    public OrgnlMsgInf1 getOrgnlMsgInf() {
        return orgnlMsgInf;
    }

    /**
     * Sets the value of the orgnlMsgInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgnlMsgInf1 }
     *     
     */
    public void setOrgnlMsgInf(OrgnlMsgInf1 value) {
        this.orgnlMsgInf = value;
    }

    /**
     * Gets the value of the bizRjctNtceInf property.
     * 
     * @return
     *     possible object is
     *     {@link BizRjctNtceInf1 }
     *     
     */
    public BizRjctNtceInf1 getBizRjctNtceInf() {
        return bizRjctNtceInf;
    }

    /**
     * Sets the value of the bizRjctNtceInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link BizRjctNtceInf1 }
     *     
     */
    public void setBizRjctNtceInf(BizRjctNtceInf1 value) {
        this.bizRjctNtceInf = value;
    }

}
