//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.21 at 05:06:38 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pain.002.001.03", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zcbspay.platform.channel.beps.bean.CustomerPaymentCancellationResponse;
